name: e_shop
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.13.12
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.0
  shimmer_animation: ^2.1.0+1
  go_router: ^14.2.7
  searchable_listview: ^2.15.1
  intl: ^0.19.0
  flutter_svg: ^2.0.5
  flutter_localizations:
    sdk: flutter
  dartx: ^1.2.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  flutter_gen_runner: null
  build_runner: null
  flutter_native_splash: ^2.0.4
  json_serializable: null
flutter_gen:
  integrations:
    flutter_svg: true
flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/logo/
  - assets/images/
