name: dummy_product
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.13.12
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.0
  shimmer_animation: ^2.1.0+1
  go_router: ^14.2.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  flutter_gen_runner: null
  build_runner: null
  flutter_native_splash: ^2.0.4
  json_serializable: null
flutter:
  uses-material-design: true
  assets:
  - assets/logo/
  - assets/images/
